#!/bin/sh
#
# kibana -- startup script for kibana4
#
# chkconfig: - 85 15
# processname: kibana
# pidfile: /var/run/kibana/kibana.pid
# description: Kibana is a webui to visualize data
#
### BEGIN INIT INFO
# Provides: kibana
# Required-Start: $local_fs $remote_fs $network
# Required-Stop: $local_fs $remote_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop kibana
### END INIT INFO
#
#
. /etc/init.d/functions

NAME="kibana"
PIDFILE="/var/run/kibana/kibana.pid"
KIBANA_DIR="/opt/kibana"
KIBANA_USER="kibana"

#if [ $? -ne 0 ] ; then
#  echo Kibana not starting. Set PID in ${KIBANA_DIR}/config/kibana.yaml
#fi

start() {
        echo -n "Starting Kibana Daemon: "
        daemon --user $KIBANA_USER --pidfile=$PIDFILE "$KIBANA_DIR/bin/$NAME"
        retval=$?
        echo
        return $retval
}

stop() {
        echo -n "Shutting down Kibana Daemon: "
        killproc -p $PIDFILE $NAME
        retval=$?
        echo
        return $retval
}

rh_status() {
    status -p $PIDFILE $NAME
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        start
        ;;
    stop)
        rh_status_q || exit 0
        stop
        ;;
    status)
        rh_status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage:  {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $?
